#pragma once
// AUTO-GENERATED by scripts/generate-planet-metadata.mjs from resource/planets.catalog.json.
// Do not edit directly — run: node scripts/generate-planet-metadata.mjs
//
// CatalogBody / CatalogSatellite / CatalogClouds consume these rows. Mercury–Pluto and
// catalog moons are constructed from this table (plus SystemVisuals for atmospheres/rings).
// Axial tilt SSOT is orbit.axialTiltDegrees, applied as Rotate(Z) then optional artTiltX.
// See docs/ARCHITECTURE.md §2.1.

#include <cstdint>

namespace BodyCatalog {

enum class Kind : uint8_t { Star = 0, Planet = 1, DwarfPlanet = 2, Satellite = 3 };
enum class OrbitPlane : uint8_t { XZ = 0, XY = 1 };

struct ShaderFlags {
    bool hasNightTexture;
    bool hasSpecularMap;
    bool hasClouds;
};

struct TextureLodIds {
    const char* diffuse;
    const char* normal;
    const char* specular; // nullptr if this body has no specular map.
    const char* night;    // nullptr if no night map (Earth).
    const char* clouds;   // nullptr if the surface shader has no cloud map.
};

struct Keplerian {
    float aKm;
    float e;
    float iDeg;
    float OmegaDeg;
    float omegaDeg;
    float M0Deg;
    float nDegPerDay;
};

struct CloudLayer {
    const char* diffuse; // nullptr => no cloud shell.
    const char* normal;
    float scaleFactor;
    float spinDegPerSimSecond;
    float ambientFactor;
};

struct Entry {
    int index;
    const char* id;
    const char* parentId; // nullptr for heliocentric bodies.
    const char* initTag;
    Kind kind;
    const wchar_t* displayNameEn;
    const wchar_t* displayNameRu;
    float auDistance;
    float orbitalPeriodDays;
    float earthRadiusScale;
    float axialTiltDegrees; // catalog SSOT; Rotate(Z) in CatalogBody.
    float artTiltXDegrees;  // Saturn ring-presentation overlay; else 0.
    float yawOffsetDegrees;
    float artRollDegrees;
    ShaderFlags shaderFlags;
    bool useSphereIntersect;
    float ambientFactor;
    TextureLodIds lod;
    const char* meshPath; // nullptr => unit sphere.
    float sceneOrbitRadius;
    OrbitPlane orbitPlane;
    float initialAnomalyRad;
    float spinDegPerSimSecond;
    Keplerian keplerian;
    CloudLayer cloudLayer;
    bool hasAtmosphere;
    bool hasCloudLayer;
    bool hasRings;
    bool atmosphereToneMapping;
    bool lightFarUsesPlanetDistance;
};

inline constexpr Entry kEntries[] = {
    {1, "mercury", "sun", "Mercury", Kind::Planet, L"Mercury", L"Меркурий", 0.387f, 88.0f, 0.38f, 0.0f, 0.0f, 0.0f, 0.0f, {false, true, false}, false, 0.0f, {"Mercury_Diffuse", "Mercury_Normal", "Mercury_Specular", nullptr, nullptr}, nullptr, 0.0f, OrbitPlane::XZ, 0.0f, 0.0f, {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, {nullptr, nullptr, 0.0f, 0.0f, 0.0f}, false, false, false, false, false}, // mercury
    {2, "venus", "sun", "Venus", Kind::Planet, L"Venus", L"Венера", 0.723f, 224.7f, 0.95f, 177.3f, 0.0f, 0.0f, 0.0f, {false, false, false}, false, 0.0f, {"Venus_Diffuse", "Venus_Normal", nullptr, nullptr, nullptr}, nullptr, 0.0f, OrbitPlane::XZ, 0.0f, 0.0f, {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, {nullptr, nullptr, 0.0f, 0.0f, 0.0f}, true, false, false, false, false}, // venus
    {3, "earth", "sun", "EarthSystem", Kind::Planet, L"Earth", L"Земля", 1.0f, 365.25f, 1.0f, -23.4f, 0.0f, 0.0f, 0.0f, {true, true, true}, false, 0.75f, {"Earth_Day_Diffuse", "Earth_Normal", "Earth_Specular", "Earth_Night_Diffuse", "Earth_Clouds_Diffuse"}, nullptr, 0.0f, OrbitPlane::XZ, 0.0f, 0.0f, {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, {"Earth_Clouds_Diffuse", "Earth_Clouds_Normal", 1.0055f, 1.125f, 1.0f}, true, true, false, false, false}, // earth
    {4, "mars", "sun", "MarsSystem", Kind::Planet, L"Mars", L"Марс", 1.524f, 687.0f, 0.53f, -25.2f, 0.0f, 0.0f, 0.0f, {false, false, false}, false, 0.0f, {"Mars_Diffuse", "Mars_Normal", nullptr, nullptr, nullptr}, nullptr, 0.0f, OrbitPlane::XZ, 0.0f, 0.0f, {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, {nullptr, nullptr, 0.0f, 0.0f, 0.0f}, true, false, false, false, true}, // mars
    {5, "jupiter", "sun", "JupiterSystem", Kind::Planet, L"Jupiter", L"Юпитер", 5.203f, 4333.0f, 11.2f, -3.1f, 0.0f, 0.0f, 0.0f, {false, false, false}, false, 0.0f, {"Jupiter_Diffuse", "Jupiter_Normal", nullptr, nullptr, nullptr}, nullptr, 0.0f, OrbitPlane::XZ, 0.0f, 0.0f, {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, {nullptr, nullptr, 0.0f, 0.0f, 0.0f}, true, false, false, true, false}, // jupiter
    {6, "saturn", "sun", "SaturnSystem", Kind::Planet, L"Saturn", L"Сатурн", 9.537f, 10759.0f, 9.45f, -26.7f, -15.0f, 0.0f, 0.0f, {false, false, false}, false, 0.0f, {"Saturn_Diffuse", "Saturn_Normal", nullptr, nullptr, nullptr}, nullptr, 0.0f, OrbitPlane::XZ, 0.0f, 0.0f, {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, {nullptr, nullptr, 0.0f, 0.0f, 0.0f}, true, false, true, true, false}, // saturn
    {7, "uranus", "sun", "UranusSystem", Kind::Planet, L"Uranus", L"Уран", 19.191f, 30687.0f, 4.0f, -97.8f, 0.0f, 0.0f, 0.0f, {false, false, true}, false, 0.0f, {"Uranus_Diffuse", "Uranus_Normal", nullptr, nullptr, "Uranus_Clouds_Diffuse"}, nullptr, 0.0f, OrbitPlane::XZ, 0.0f, 0.0f, {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, {"Uranus_Clouds_Diffuse", "Uranus_Clouds_Normal", 3.98635f, 3.447f, 0.0f}, true, true, true, true, false}, // uranus
    {8, "neptune", "sun", "NeptuneSystem", Kind::Planet, L"Neptune", L"Нептун", 30.069f, 60190.0f, 3.88f, -28.3f, 0.0f, 0.0f, 0.0f, {false, false, true}, false, 0.0f, {"Neptune_Diffuse", "Neptune_Normal", nullptr, nullptr, "Neptune_Clouds_Diffuse"}, nullptr, 0.0f, OrbitPlane::XZ, 0.0f, 0.0f, {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, {"Neptune_Clouds_Diffuse", "Neptune_Clouds_Normal", 3.87f, 4.8f, 0.0f}, true, true, false, true, false}, // neptune
    {9, "pluto", "sun", "PlutoSystem", Kind::DwarfPlanet, L"Pluto", L"Плутон", 39.482f, 90560.0f, 0.18f, -122.5f, 0.0f, 0.0f, 0.0f, {false, true, false}, false, 0.0f, {"Pluto_Diffuse", "Pluto_Normal", "Pluto_Specular", nullptr, nullptr}, nullptr, 0.0f, OrbitPlane::XZ, 0.0f, 0.0f, {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, {nullptr, nullptr, 0.0f, 0.0f, 0.0f}, true, false, false, true, false}, // pluto
    {10, "ceres", "sun", "Ceres", Kind::DwarfPlanet, L"Ceres", L"Церера", 2.7656f, 1679.85f, 0.0736f, 4.0f, 0.0f, 0.0f, 0.0f, {false, false, false}, false, 0.0f, {"Ceres_Diffuse", "Ceres_Normal", nullptr, nullptr, nullptr}, nullptr, 0.0f, OrbitPlane::XZ, 0.0f, 0.0f, {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, {nullptr, nullptr, 0.0f, 0.0f, 0.0f}, false, false, false, false, false}, // ceres
    {11, "vesta", "sun", "Vesta", Kind::DwarfPlanet, L"Vesta", L"Веста", 2.3614f, 1325.39f, 0.0412f, 27.0f, 0.0f, 0.0f, 0.0f, {false, false, false}, false, 0.0f, {"Vesta_Diffuse", "Vesta_Normal", nullptr, nullptr, nullptr}, nullptr, 0.0f, OrbitPlane::XZ, 0.0f, 0.0f, {0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f}, {nullptr, nullptr, 0.0f, 0.0f, 0.0f}, false, false, false, false, false}, // vesta
    {12, "moon", "earth", "EarthSystem", Kind::Satellite, L"Moon", L"Луна", 0.0025695552897999907f, 27.3f, 0.2724f, 0.0f, 0.0f, -75.0f, 0.0f, {false, false, false}, true, 0.0f, {"Moon_Diffuse", "Moon_Normal", nullptr, nullptr, nullptr}, nullptr, 25.0f, OrbitPlane::XZ, -1.57079633f, -0.69f, {384400.0f, 0.0549f, 5.145f, 125.08f, 318.15f, 135.27f, 13.186813186813186f}, {nullptr, nullptr, 0.0f, 0.0f, 0.0f}, false, false, false, false, false}, // moon
    {13, "phobos", "mars", "MarsSystem", Kind::Satellite, L"Phobos", L"Фобос", 0.00006267468885838895f, 0.3189f, 0.001768f, 0.0f, 0.0f, 0.0f, 0.0f, {false, false, false}, true, 0.0f, {"Phobos_Diffuse", "Phobos_Normal", nullptr, nullptr, nullptr}, "resource/models/phobos.obj", 2.5f, OrbitPlane::XZ, -1.57079633f, -7.56f, {9376.0f, 0.0151f, 1.093f, 199.42f, 150.21f, 0.0f, 1128.8805268109124f}, {nullptr, nullptr, 0.0f, 0.0f, 0.0f}, false, false, false, false, false}, // phobos
    {14, "deimos", "mars", "MarsSystem", Kind::Satellite, L"Deimos", L"Деймос", 0.00015684046764978456f, 1.263f, 0.00097316f, 0.0f, 0.0f, 0.0f, 0.0f, {false, false, false}, true, 0.0f, {"Deimos_Diffuse", "Deimos_Normal", nullptr, nullptr, nullptr}, "resource/models/deimos.obj", 2.95f, OrbitPlane::XZ, -1.57079633f, -2.76f, {23463.0f, 0.00033f, 0.93f, 54.5f, 0.0f, 0.0f, 285.03562945368174f}, {nullptr, nullptr, 0.0f, 0.0f, 0.0f}, false, false, false, false, false}, // deimos
    {15, "io", "jupiter", "JupiterSystem", Kind::Satellite, L"Io", L"Ио", 0.0028195588481728304f, 1.769f, 0.28592f, 0.0f, 0.0f, 0.0f, 0.0f, {false, false, false}, true, 0.0f, {"Io_Diffuse", "Io_Normal", nullptr, nullptr, nullptr}, nullptr, 65.0f, OrbitPlane::XZ, -1.57079633f, -2.76f, {421800.0f, 0.0041f, 0.05f, 43.98f, 84.5f, 342.0f, 203.50480497456192f}, {nullptr, nullptr, 0.0f, 0.0f, 0.0f}, false, false, false, false, false}, // io
    {16, "europa", "jupiter", "JupiterSystem", Kind::Satellite, L"Europa", L"Европа", 0.004486026417754354f, 3.551f, 0.244985f, 0.0f, 0.0f, 0.0f, 0.0f, {false, false, false}, true, 0.0f, {"Europa_Diffuse", "Europa_Normal", nullptr, nullptr, nullptr}, nullptr, 74.0f, OrbitPlane::XZ, -1.57079633f, -2.76f, {671100.0f, 0.009f, 0.47f, 219.1f, 88.97f, 171.0f, 101.37989298789073f}, {nullptr, nullptr, 0.0f, 0.0f, 0.0f}, false, false, false, false, false}, // europa
    {17, "ganymede", "jupiter", "JupiterSystem", Kind::Satellite, L"Ganymede", L"Ганимед", 0.007155182055676145f, 7.155f, 0.41345f, 0.0f, 0.0f, 0.0f, 0.0f, {false, false, false}, true, 0.0f, {"Ganymede_Diffuse", "Ganymede_Normal", nullptr, nullptr, nullptr}, nullptr, 83.0f, OrbitPlane::XZ, -1.57079633f, -2.76f, {1070400.0f, 0.0013f, 0.2f, 63.55f, 192.4f, 317.3f, 50.31446540880503f}, {nullptr, nullptr, 0.0f, 0.0f, 0.0f}, false, false, false, false, false}, // ganymede
    {18, "callisto", "jupiter", "JupiterSystem", Kind::Satellite, L"Callisto", L"Каллисто", 0.012585072175094802f, 16.69f, 0.3783236f, 0.0f, 0.0f, 0.0f, 0.0f, {false, false, false}, true, 0.0f, {"Callisto_Diffuse", "Callisto_Normal", nullptr, nullptr, nullptr}, nullptr, 92.0f, OrbitPlane::XZ, -1.57079633f, -2.76f, {1882700.0f, 0.0074f, 0.192f, 298.85f, 52.64f, 181.4f, 21.56980227681246f}, {nullptr, nullptr, 0.0f, 0.0f, 0.0f}, false, false, false, false, false}, // callisto
    {19, "mimas", "saturn", "SaturnSystem", Kind::Satellite, L"Mimas", L"Мимас", 0.0012402516100785653f, 0.942f, 0.03111f, 0.0f, 0.0f, 0.0f, 0.0f, {false, false, false}, true, 0.0f, {"Mimas_Diffuse", "Mimas_Normal", nullptr, nullptr, nullptr}, nullptr, 60.5f, OrbitPlane::XZ, -1.57079633f, -2.76f, {185539.0f, 0.0196f, 1.574f, 0.0f, 0.0f, 0.0f, 382.1656050955414f}, {nullptr, nullptr, 0.0f, 0.0f, 0.0f}, false, false, false, false, false}, // mimas
    {20, "enceladus", "saturn", "SaturnSystem", Kind::Satellite, L"Enceladus", L"Энцелад", 0.0015905841365695323f, 1.37f, 0.03957f, 0.0f, 0.0f, 0.0f, 0.0f, {false, false, false}, true, 0.0f, {"Enceladus_Diffuse", "Enceladus_Normal", nullptr, nullptr, nullptr}, nullptr, 65.0f, OrbitPlane::XZ, -1.57079633f, -2.76f, {237948.0f, 0.0047f, 0.009f, 0.0f, 0.0f, 0.0f, 262.7737226277372f}, {nullptr, nullptr, 0.0f, 0.0f, 0.0f}, false, false, false, false, false}, // enceladus
    {21, "tethys", "saturn", "SaturnSystem", Kind::Satellite, L"Tethys", L"Тефия", 0.0019694063733756073f, 1.888f, 0.083346f, 0.0f, 0.0f, 0.0f, 0.0f, {false, false, false}, true, 0.0f, {"Tethys_Diffuse", "Tethys_Normal", nullptr, nullptr, nullptr}, nullptr, 69.5f, OrbitPlane::XZ, -1.57079633f, -2.76f, {294619.0f, 0.0001f, 1.12f, 0.0f, 0.0f, 0.0f, 190.67796610169492f}, {nullptr, nullptr, 0.0f, 0.0f, 0.0f}, false, false, false, false, false}, // tethys
    {22, "dione", "saturn", "SaturnSystem", Kind::Satellite, L"Dione", L"Диона", 0.0025227364415956223f, 2.737f, 0.08812f, 0.0f, 0.0f, 0.0f, 0.0f, {false, false, false}, true, 0.0f, {"Dione_Diffuse", "Dione_Normal", nullptr, nullptr, nullptr}, nullptr, 74.0f, OrbitPlane::XZ, -1.57079633f, -2.76f, {377396.0f, 0.0022f, 0.019f, 0.0f, 0.0f, 0.0f, 131.53087321885275f}, {nullptr, nullptr, 0.0f, 0.0f, 0.0f}, false, false, false, false, false}, // dione
    {23, "rhea", "saturn", "SaturnSystem", Kind::Satellite, L"Rhea", L"Рея", 0.003523499348844676f, 4.518f, 0.119886f, 0.0f, 0.0f, 0.0f, 0.0f, {false, false, false}, true, 0.0f, {"Rhea_Diffuse", "Rhea_Normal", nullptr, nullptr, nullptr}, nullptr, 78.5f, OrbitPlane::XZ, -1.57079633f, -2.76f, {527108.0f, 0.0013f, 0.345f, 0.0f, 0.0f, 0.0f, 79.6812749003984f}, {nullptr, nullptr, 0.0f, 0.0f, 0.0f}, false, false, false, false, false}, // rhea
    {24, "titan", "saturn", "SaturnSystem", Kind::Satellite, L"Titan", L"Титан", 0.008167696467086146f, 15.95f, 0.404136f, 0.0f, 0.0f, 0.0f, 0.0f, {false, false, false}, true, 0.0f, {"Titan_Diffuse", "Titan_Normal", nullptr, nullptr, nullptr}, nullptr, 87.5f, OrbitPlane::XZ, -1.57079633f, -2.76f, {1221870.0f, 0.0288f, 0.3485f, 28.06f, 180.53f, 163.31f, 22.570532915360502f}, {nullptr, nullptr, 0.0f, 0.0f, 0.0f}, false, false, false, false, false}, // titan
    {25, "iapetus", "saturn", "SaturnSystem", Kind::Satellite, L"Iapetus", L"Япет", 0.02380261151671593f, 79.32f, 0.115288f, 0.0f, 0.0f, 0.0f, 0.0f, {false, false, false}, true, 0.0f, {"Iapetus_Diffuse", "Iapetus_Normal", nullptr, nullptr, nullptr}, nullptr, 96.5f, OrbitPlane::XZ, -1.57079633f, -2.76f, {3560820.0f, 0.0286f, 15.47f, 0.0f, 0.0f, 0.0f, 4.538577912254161f}, {nullptr, nullptr, 0.0f, 0.0f, 0.0f}, false, false, false, false, false}, // iapetus
    {26, "miranda", "uranus", "UranusSystem", Kind::Satellite, L"Miranda", L"Миранда", 0.0008649187277503142f, 1.413f, 0.0368858f, 0.0f, 0.0f, 0.0f, 90.0f, {false, false, false}, true, 0.0f, {"Miranda_Diffuse", "Miranda_Normal", nullptr, nullptr, nullptr}, nullptr, 34.8f, OrbitPlane::XY, 3.14159265f, -2.76f, {129390.0f, 0.0013f, 4.338f, 0.0f, 0.0f, 0.0f, 254.77707006369425f}, {nullptr, nullptr, 0.0f, 0.0f, 0.0f}, false, false, false, false, false}, // miranda
    {27, "ariel", "uranus", "UranusSystem", Kind::Satellite, L"Ariel", L"Ариэль", 0.0012768898320957185f, 2.52f, 0.090865f, 0.0f, 0.0f, 0.0f, 90.0f, {false, false, false}, true, 0.0f, {"Ariel_Diffuse", "Ariel_Normal", nullptr, nullptr, nullptr}, nullptr, 44.0f, OrbitPlane::XY, 3.14159265f, -2.76f, {191020.0f, 0.0012f, 0.041f, 0.0f, 0.0f, 0.0f, 142.85714285714286f}, {nullptr, nullptr, 0.0f, 0.0f, 0.0f}, false, false, false, false, false}, // ariel
    {28, "umbriel", "uranus", "UranusSystem", Kind::Satellite, L"Umbriel", L"Умбриэль", 0.0017781001745234067f, 4.144f, 0.091775f, 0.0f, 0.0f, 0.0f, 90.0f, {false, false, false}, true, 0.0f, {"Umbriel_Diffuse", "Umbriel_Normal", nullptr, nullptr, nullptr}, nullptr, 49.0f, OrbitPlane::XY, 3.14159265f, -2.76f, {266000.0f, 0.0039f, 0.128f, 0.0f, 0.0f, 0.0f, 86.87258687258687f}, {nullptr, nullptr, 0.0f, 0.0f, 0.0f}, false, false, false, false, false}, // umbriel
    {29, "titania", "uranus", "UranusSystem", Kind::Satellite, L"Titania", L"Титания", 0.002913878372468038f, 8.706f, 0.123748f, 0.0f, 0.0f, 0.0f, 90.0f, {false, false, false}, true, 0.0f, {"Titania_Diffuse", "Titania_Normal", nullptr, nullptr, nullptr}, nullptr, 55.0f, OrbitPlane::XY, 3.14159265f, -2.76f, {435910.0f, 0.0011f, 0.079f, 0.0f, 0.0f, 0.0f, 41.35079255685734f}, {nullptr, nullptr, 0.0f, 0.0f, 0.0f}, false, false, false, false, false}, // titania
    {30, "oberon", "uranus", "UranusSystem", Kind::Satellite, L"Oberon", L"Оберон", 0.0039005902775860837f, 13.46f, 0.11951f, 0.0f, 0.0f, 0.0f, 90.0f, {false, false, false}, true, 0.0f, {"Oberon_Diffuse", "Oberon_Normal", nullptr, nullptr, nullptr}, nullptr, 61.0f, OrbitPlane::XY, 3.14159265f, -2.76f, {583520.0f, 0.0014f, 0.068f, 0.0f, 0.0f, 0.0f, 26.745913818722137f}, {nullptr, nullptr, 0.0f, 0.0f, 0.0f}, false, false, false, false, false}, // oberon
    {31, "triton", "neptune", "NeptuneSystem", Kind::Satellite, L"Triton", L"Тритон", 0.002371417442908832f, 5.877f, 0.2724f, 0.0f, 0.0f, -75.0f, 0.0f, {false, false, false}, true, 0.0f, {"Triton_Diffuse", "Triton_Normal", nullptr, nullptr, nullptr}, nullptr, 37.5f, OrbitPlane::XZ, -1.57079633f, -2.76f, {354759.0f, 0.000016f, 156.885f, 177.61f, 66.14f, 260.64f, 61.25574272588055f}, {nullptr, nullptr, 0.0f, 0.0f, 0.0f}, false, false, false, false, false}, // triton
    {32, "charon", "pluto", "PlutoSystem", Kind::Satellite, L"Charon", L"Харон", 0.00013095774631236113f, 6.387f, 0.09512f, 0.0f, 0.0f, -75.0f, 0.0f, {false, true, false}, true, 0.0f, {"Charon_Diffuse", "Charon_Normal", "Charon_Specular", nullptr, nullptr}, nullptr, 25.0f, OrbitPlane::XZ, -1.57079633f, -2.76f, {19591.0f, 0.0002f, 0.08f, 223.05f, 0.0f, 0.0f, 56.36449037106623f}, {nullptr, nullptr, 0.0f, 0.0f, 0.0f}, false, false, false, false, false}, // charon
};

inline constexpr bool StrEq(const char* a, const char* b) {
    if (!a || !b) {
        return a == b;
    }
    while (*a && *a == *b) {
        ++a;
        ++b;
    }
    return *a == *b;
}

/** Row for a catalog index, or nullptr when that body has no render descriptor. */
inline constexpr const Entry* FindByIndex(int index) {
    for (const Entry& entry : kEntries) {
        if (entry.index == index) {
            return &entry;
        }
    }
    return nullptr;
}

inline constexpr const Entry* FindById(const char* id) {
    for (const Entry& entry : kEntries) {
        if (StrEq(entry.id, id)) {
            return &entry;
        }
    }
    return nullptr;
}

/** Primary (non-satellite) body for a staged-loading initTag, or nullptr. */
inline constexpr const Entry* FindPrimaryByInitTag(const char* initTag) {
    for (const Entry& entry : kEntries) {
        if (entry.kind != Kind::Satellite && StrEq(entry.initTag, initTag)) {
            return &entry;
        }
    }
    return nullptr;
}

} // namespace BodyCatalog
