#pragma once
// AUTO-GENERATED by scripts/generate-planet-metadata.mjs from resource/planets.catalog.json.
// Do not edit directly — run: node scripts/generate-planet-metadata.mjs
//
// Render descriptors for catalog bodies with no unique shader needs (see the `render`
// block in planets.catalog.json). Consumed by Solar_System/CatalogBody, which builds a
// renderable body straight from a row — that is how Ceres and Vesta exist without a C++
// class of their own. Rows for the eight planets and Pluto are not yet used: those still
// have hand-written classes that hardcode the same values, and can migrate one at a time.
// The Sun, ring systems, and moons remain hand-maintained; moons are not in the catalog.
//
// Deliberately excludes axial tilt — see OrbitLayoutBodies.generated.inc header comment
// for why catalog orbit.axialTiltDegrees cannot drive this without a reconciliation pass.
// earthRadiusScale carries the same caveat: authoritative only for CatalogBody bodies,
// because each hand-written planet class passes its own coefficient to PlanetInfo.

#include <cstdint>

namespace BodyCatalog {

struct ShaderFlags {
    bool hasNightTexture;
    bool hasSpecularMap;
    bool hasClouds;
};

struct TextureLodIds {
    const char* diffuse;
    const char* normal;
    const char* specular; // nullptr if this body has no specular map.
};

struct Entry {
    int index;
    const char* id;
    const char* initTag;
    const wchar_t* displayNameEn;
    const wchar_t* displayNameRu;
    float auDistance;
    float orbitalPeriodDays;
    float earthRadiusScale;
    ShaderFlags shaderFlags;
    float ambientFactor;
    TextureLodIds lod;
};

inline constexpr Entry kEntries[] = {
    {1, "mercury", "Mercury", L"Mercury", L"Меркурий", 0.387f, 88.0f, 0.38f, {false, true, false}, 0.0f, {"Mercury_Diffuse", "Mercury_Normal", "Mercury_Specular"}}, // mercury
    {2, "venus", "Venus", L"Venus", L"Венера", 0.723f, 224.7f, 0.95f, {false, false, false}, 0.0f, {"Venus_Diffuse", "Venus_Normal", nullptr}}, // venus
    {3, "earth", "EarthSystem", L"Earth", L"Земля", 1.0f, 365.25f, 1.0f, {true, true, true}, 0.75f, {"Earth_Day_Diffuse", "Earth_Normal", "Earth_Specular"}}, // earth
    {4, "mars", "MarsSystem", L"Mars", L"Марс", 1.524f, 687.0f, 0.53f, {false, false, false}, 0.0f, {"Mars_Diffuse", "Mars_Normal", nullptr}}, // mars
    {5, "jupiter", "JupiterSystem", L"Jupiter", L"Юпитер", 5.203f, 4333.0f, 11.2f, {false, false, false}, 0.0f, {"Jupiter_Diffuse", "Jupiter_Normal", nullptr}}, // jupiter
    {6, "saturn", "SaturnSystem", L"Saturn", L"Сатурн", 9.537f, 10759.0f, 9.45f, {false, false, false}, 0.0f, {"Saturn_Diffuse", "Saturn_Normal", nullptr}}, // saturn
    {7, "uranus", "UranusSystem", L"Uranus", L"Уран", 19.191f, 30687.0f, 4.0f, {false, false, true}, 0.0f, {"Uranus_Diffuse", "Uranus_Normal", nullptr}}, // uranus
    {8, "neptune", "NeptuneSystem", L"Neptune", L"Нептун", 30.069f, 60190.0f, 3.88f, {false, false, true}, 0.0f, {"Neptune_Diffuse", "Neptune_Normal", nullptr}}, // neptune
    {9, "pluto", "PlutoSystem", L"Pluto", L"Плутон", 39.482f, 90560.0f, 0.18f, {false, true, false}, 0.0f, {"Pluto_Diffuse", "Pluto_Normal", "Pluto_Specular"}}, // pluto
    {10, "ceres", "Ceres", L"Ceres", L"Церера", 2.7656f, 1679.85f, 0.0736f, {false, false, false}, 0.0f, {"Ceres_Diffuse", "Ceres_Normal", nullptr}}, // ceres
    {11, "vesta", "Vesta", L"Vesta", L"Веста", 2.3614f, 1325.39f, 0.0412f, {false, false, false}, 0.0f, {"Vesta_Diffuse", "Vesta_Normal", nullptr}}, // vesta
};

/** Row for a focus index, or nullptr when that body has no render descriptor. */
inline constexpr const Entry* FindByIndex(int index) {
    for (const Entry& entry : kEntries) {
        if (entry.index == index) {
            return &entry;
        }
    }
    return nullptr;
}

} // namespace BodyCatalog
