import './style.css'
// SolarSystem.js will be generated by Emscripten
import Module from './SolarSystem.js'

const canvas = document.getElementById('canvas') as HTMLCanvasElement;

const moduleConfig = {
    canvas: canvas,
    print: (text: string) => console.log(text),
    printErr: (text: string) => console.error(text),
    onRuntimeInitialized: () => {
        console.log('SolarSystem WASM initialized');
    }
};

// @ts-ignore
Module(moduleConfig);
