// AUTO-GENERATED by scripts/generate-wasm-exports.mjs — do not edit.
import type { SolarSystemCwrap } from './SolarSystem.js';

export interface CachedCwrapExports {
    setCameraPose: (...args: number[]) => void;
    setQualityPreset: (...args: number[]) => void;
    getQualityPreset: () => number;
    setTimeScale: (...args: number[]) => void;
    getTimeScale: () => number;
    setPaused: (...args: number[]) => void;
    getPaused: () => number;
    setSimulationEpoch: (...args: number[]) => void;
    getSimulationEpoch: () => number;
    setShadowQuality: (...args: number[]) => void;
    getShadowQuality: () => number;
    setTouchMovement: (...args: number[]) => void;
    addTouchLook: (...args: number[]) => void;
    addTouchZoom: (...args: number[]) => void;
    isMobileWeb: () => number;
    setMusicVolume: (...args: number[]) => void;
    getMusicVolume: () => number;
    setMusicMuted: (...args: number[]) => void;
    getMusicMuted: () => number;
    focusPlanet: (...args: number[]) => void;
    setOrbitScaleMode: (...args: number[]) => void;
    getOrbitScaleMode: () => number;
    getNearestPlanetIndex: () => number;
    getFocusedPlanetIndex: () => number;
    getPlanetSceneDistance: (...args: number[]) => number;
    setOrbitLines: (...args: number[]) => void;
    getOrbitLines: () => number;
    setMagneticFields: (...args: number[]) => void;
    getMagneticFields: () => number;
    setMagneticFieldMode: (...args: number[]) => void;
    getMagneticFieldMode: () => number;
    setXrSessionActive: (...args: number[]) => void;
    setXrEyeCount: (...args: number[]) => void;
    setXrEyeViewport: (...args: number[]) => void;
    getXrMatrixScratch: () => number;
    commitXrEyeMatrices: (...args: number[]) => void;
    runXrFrame: () => void;
    getCameraPositionX: () => number;
    getCameraPositionY: () => number;
    getCameraPositionZ: () => number;
    getCameraYaw: () => number;
    getCameraPitch: () => number;
}

export function createCachedCwrapExports(cwrap: SolarSystemCwrap): CachedCwrapExports {
    return {
    setCameraPose: cwrap('SetCameraPose', null, ['number', 'number', 'number', 'number', 'number']) as (...args: number[]) => void,
    setQualityPreset: cwrap('SetQualityPreset', null, ['number']) as (...args: number[]) => void,
    getQualityPreset: cwrap('GetQualityPreset', 'number', []) as () => number,
    setTimeScale: cwrap('SetTimeScale', null, ['number']) as (...args: number[]) => void,
    getTimeScale: cwrap('GetTimeScale', 'number', []) as () => number,
    setPaused: cwrap('SetPaused', null, ['number']) as (...args: number[]) => void,
    getPaused: cwrap('GetPaused', 'number', []) as () => number,
    setSimulationEpoch: cwrap('SetSimulationEpoch', null, ['number']) as (...args: number[]) => void,
    getSimulationEpoch: cwrap('GetSimulationEpoch', 'number', []) as () => number,
    setShadowQuality: cwrap('SetShadowQuality', null, ['number']) as (...args: number[]) => void,
    getShadowQuality: cwrap('GetShadowQuality', 'number', []) as () => number,
    setTouchMovement: cwrap('SetTouchMovement', null, ['number', 'number', 'number']) as (...args: number[]) => void,
    addTouchLook: cwrap('AddTouchLook', null, ['number', 'number']) as (...args: number[]) => void,
    addTouchZoom: cwrap('AddTouchZoom', null, ['number']) as (...args: number[]) => void,
    isMobileWeb: cwrap('IsMobileWeb', 'number', []) as () => number,
    setMusicVolume: cwrap('SetMusicVolume', null, ['number']) as (...args: number[]) => void,
    getMusicVolume: cwrap('GetMusicVolume', 'number', []) as () => number,
    setMusicMuted: cwrap('SetMusicMuted', null, ['number']) as (...args: number[]) => void,
    getMusicMuted: cwrap('GetMusicMuted', 'number', []) as () => number,
    focusPlanet: cwrap('FocusPlanet', null, ['number']) as (...args: number[]) => void,
    setOrbitScaleMode: cwrap('SetOrbitScaleMode', null, ['number']) as (...args: number[]) => void,
    getOrbitScaleMode: cwrap('GetOrbitScaleMode', 'number', []) as () => number,
    getNearestPlanetIndex: cwrap('GetNearestPlanetIndex', 'number', []) as () => number,
    getFocusedPlanetIndex: cwrap('GetFocusedPlanetIndex', 'number', []) as () => number,
    getPlanetSceneDistance: cwrap('GetPlanetSceneDistance', 'number', ['number']) as (...args: number[]) => number,
    setOrbitLines: cwrap('SetOrbitLines', null, ['number']) as (...args: number[]) => void,
    getOrbitLines: cwrap('GetOrbitLines', 'number', []) as () => number,
    setMagneticFields: cwrap('SetMagneticFields', null, ['number']) as (...args: number[]) => void,
    getMagneticFields: cwrap('GetMagneticFields', 'number', []) as () => number,
    setMagneticFieldMode: cwrap('SetMagneticFieldMode', null, ['number']) as (...args: number[]) => void,
    getMagneticFieldMode: cwrap('GetMagneticFieldMode', 'number', []) as () => number,
    setXrSessionActive: cwrap('SetXrSessionActive', null, ['number']) as (...args: number[]) => void,
    setXrEyeCount: cwrap('SetXrEyeCount', null, ['number']) as (...args: number[]) => void,
    setXrEyeViewport: cwrap('SetXrEyeViewport', null, ['number', 'number', 'number', 'number', 'number']) as (...args: number[]) => void,
    getXrMatrixScratch: cwrap('GetXrMatrixScratch', 'number', []) as () => number,
    commitXrEyeMatrices: cwrap('CommitXrEyeMatrices', null, ['number']) as (...args: number[]) => void,
    runXrFrame: cwrap('RunXrFrame', null, []) as () => void,
    getCameraPositionX: cwrap('GetCameraPositionX', 'number', []) as () => number,
    getCameraPositionY: cwrap('GetCameraPositionY', 'number', []) as () => number,
    getCameraPositionZ: cwrap('GetCameraPositionZ', 'number', []) as () => number,
    getCameraYaw: cwrap('GetCameraYaw', 'number', []) as () => number,
    getCameraPitch: cwrap('GetCameraPitch', 'number', []) as () => number,
    };
}

export const EXPORT_COUNT = 42;
